In [13]:
#EL ARCHIVO CARGADO DEBE ACTUALIZARSE AL MENOS MENSUALMENTE CON LOS PACIENTES NUEVOS

import numpy as np
import pandas as pd

from IPython.display import display
pd.options.display.max_columns = None

pd.set_option("display.max_rows",1000)

bday_df = pd.read_csv('ClinicCloud Ventas Con FechaNac.csv', engine='python')
bday_df.head(3)

,Nombre_Clinica,nombre,apellidos,dni,tele1,tele2,fechanac,TotalPagos,Num. Presupuesto,Fecha Presupuesto
0,Autopista 104A Bogota,Margarita,ojeda rios,37242086,3124056889,3118897350,09/06/1950,866903,71.0,09/03/2015
1,Autopista 104A Bogota,jose alfonso,puentes babativa,19097817,3132780412,NaN,25/06/1998,218103,84.0,09/03/2015
2,Autopista 104A Bogota,Sandra Patricia,Sanchez Tellez,52537051,3105572267,NaN,23/08/1979,6345838,85.0,09/03/2015

In [14]:
bday_df['bday']=None
bday_df['fecha_ref']='30/07'

bday_df['bday']=bday_df['fechanac'].str.slice(start=0,stop=5)
bday_df=bday_df[bday_df['bday']==bday_df['fecha_ref']]
#bday_df=bday_df.set_index('Nombre_Clinica')
bday_df=bday_df[['Nombre_Clinica','nombre','apellidos','tele1','tele2','fechanac','TotalPagos','Fecha Presupuesto']]
bday_df=bday_df.reset_index()
bday_df.head()

,index,Nombre_Clinica,nombre,apellidos,tele1,tele2,fechanac,TotalPagos,Fecha Presupuesto
0,101,Autopista 104A Bogota,marina,torres chaparro,3133171629,8125981,30/07/1943,749383,24/03/2015
1,420,Autopista 104A Bogota,MARIA DEL ROCIO,ORREGO VALENCIA,3158424286,6291051,30/07/1957,250000,10/07/2015
2,627,Autopista 104A Bogota,Mireya,Alcid Sanchez,111111111,6432799,30/07/1944,510250,02/09/2015
3,660,Autopista 104A Bogota,german,correa gutierez,3143239466,NaN,30/07/1979,1300000,08/08/2015
4,986,Autopista 104A Bogota,Jose Andres,Gomez,3045335819,5231634,30/07/1979,1011700,25/11/2015

In [15]:
# generacion de reportes

clinicas = bday_df['Nombre_Clinica'].unique()

for i in clinicas:
    temp_df = bday_df[bday_df['Nombre_Clinica'] == i]
    temp_df.to_csv('cumple %s.csv' % i, index = False)                  
                              
bday_df.to_csv('cumpleanos.csv', index = False)
print("Archivos generados!")

Archivos generados!